spring:
  # mysql + druid配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL驱动
    url: jdbc:mysql://localhost:3306/train?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC  # 数据库连接URL
    username: admin_train  # 数据库用户名
    password: 123456  # 数据库密码
    type: com.alibaba.druid.pool.DruidDataSource  # 数据源类型为Druid
    druid:
      initial-size: 5  # 初始连接数
      max-active: 20  # 最大连接数
      min-idle: 5  # 最小空闲连接数
      max-wait: 60000  # 获取连接的最大等待时间（毫秒）
      time-between-eviction-runs-millis: 60000  # 连接池中的连接检测时间间隔（毫秒）
      min-evictable-idle-time-millis: 300000  # 连接在池中最小生存时间（毫秒）
      validation-query: SELECT 1 FROM DUAL  # 验证连接有效性的SQL查询
      test-while-idle: true  # 是否在空闲时测试连接有效性
      test-on-borrow: false  # 是否在借用连接时测试连接有效性
      test-on-return: false  # 是否在归还连接时测试连接有效性
      pool-prepared-statements: true  # 是否打开PSCache
      max-pool-prepared-statement-per-connection-size: 20  # 每个连接上PSCache的大小
      filters: stat,wall,log4j  # 过滤器，用于监控统计、防SQL注入、日志记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 连接属性，配置SQL合并和慢SQL记录


  data:
    # Redis配置
    redis:
      host: 192.168.154.132
      port: 6379
      password: chakra  # 如果没有密码，可以省略这一行
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
      timeout: 6000
    mongodb:
      username: root
      password: root
      host: 192.168.154.132


# mybatis-plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    auto-mapping-unknown-column-behavior: warning
    arg-name-based-constructor-auto-mapping: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
  type-aliases-package: com.superchakra.train.entity

